// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.SharedKernel.Tenancy;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class EcheanceDesFournisseurs : ITenantEntity
{
    public int Id { get; set; }

    public string TenantId { get; set; } = TenantConstants.DefaultTenantId;

    public DateTime DateEcheance { get; set; }

    public long NumCheque { get; set; }

    public decimal Montant { get; set; }

    public int FournisseurId { get; set; }

    public virtual Fournisseur Fournisseur { get; set; } = null!;
}