// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.SharedKernel.Tenancy;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class FactureAvoirFournisseur : IAccountingYearEntity, ITenantEntity
{
    public static FactureAvoirFournisseur CreateFactureAvoirFournisseur(
        int numFactureAvoirFourSurPage,
        int idFournisseur,
        DateTime date,
        int? factureFournisseurId,
        int accountingYearId)
    {
        return new FactureAvoirFournisseur
        {
            NumFactureAvoirFourSurPage = numFactureAvoirFourSurPage,
            IdFournisseur = idFournisseur,
            Date = date,
            FactureFournisseurId = factureFournisseurId,
            AccountingYearId = accountingYearId,
            Statut = DocumentStatus.Draft
        };
    }

    public void Valider()
    {
        if (Statut != DocumentStatus.Draft)
        {
            throw new InvalidOperationException("Seul un document en brouillon peut être validé.");
        }
        Statut = DocumentStatus.Valid;
    }

    public void UpdateFactureAvoirFournisseur(
        int numFactureAvoirFourSurPage,
        int idFournisseur,
        DateTime date,
        int? factureFournisseurId,
        int accountingYearId)
    {
        this.NumFactureAvoirFourSurPage = numFactureAvoirFourSurPage;
        this.IdFournisseur = idFournisseur;
        this.Date = date;
        this.FactureFournisseurId = factureFournisseurId;
        this.AccountingYearId = accountingYearId;
    }

    public int Id { get; set; }

    public string TenantId { get; set; } = TenantConstants.DefaultTenantId;

    public int NumFactureAvoirFourSurPage { get; set; }

    public int IdFournisseur { get; set; }

    public DateTime Date { get; set; }

    public int? FactureFournisseurId { get; set; }

    public int AccountingYearId { get; set; }

    public DocumentStatus Statut { get; private set; }

    public virtual Fournisseur IdFournisseurNavigation { get; set; } = null!;

    public virtual AccountingYear AccountingYear { get; set; } = null!;

    public virtual ICollection<AvoirFournisseur> AvoirFournisseur { get; set; } = new List<AvoirFournisseur>();

    public virtual FactureFournisseur? FactureFournisseurNavigation { get; set; }
}