// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.SharedKernel.Tenancy;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class LigneCommandes : ITenantEntity
{
    public int IdLi { get; set; }

    public string TenantId { get; set; } = TenantConstants.DefaultTenantId;

    public int NumCommande { get; set; }

    public string RefProduit { get; set; } = null!;

    public string? DesignationLi { get; set; }

    public int QteLi { get; set; }

    public decimal PrixHt { get; set; }

    public double Remise { get; set; }

    public decimal TotHt { get; set; }

    public double Tva { get; set; }

    public decimal TotTtc { get; set; }

    public virtual Commandes NumCommandeNavigation { get; set; } = null!;

    public virtual Produit RefProduitNavigation { get; set; } = null!;
}