// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.SharedKernel.Tenancy;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Transaction : ITenantEntity
{
    public int BonDeLivraisonId { get; set; }

    public string TenantId { get; set; } = TenantConstants.DefaultTenantId;

    public int Type { get; set; }

    public DateTime DateTr { get; set; }

    public decimal Montant { get; set; }

    public virtual BonDeLivraison NumBlNavigation { get; set; } = null!;
}