# ==============================================================================
# Services for Production Environment - Nizar
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: silkroad-api-service-nizar
  namespace: silkroad-prod-nizar
  labels:
    app: silkroad-api-nizar
    environment: production
spec:
  type: ClusterIP
  selector:
    app: silkroad-api-nizar
    environment: production
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: silkroad-webapp-service-nizar
  namespace: silkroad-prod-nizar
  labels:
    app: silkroad-webapp-nizar
    environment: production
spec:
  type: ClusterIP
  selector:
    app: silkroad-webapp-nizar
    environment: production
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None