namespace TunNetCom.SilkRoadErp.Sales.Api.Features.priceQuote.CreatePriceQuote;

public class CreatePriceQuoteCommandHandler(
    SalesContext _context,
    ILogger<CreatePriceQuoteCommandHandler> _logger)
    : IRequestHandler<CreatePriceQuoteCommand, Result<int>>
{
    public async Task<Result<int>> Handle(CreatePriceQuoteCommand createPriceQuoteCommand, CancellationToken cancellationToken)
    {
        _logger.LogEntityCreated(nameof(Devis), createPriceQuoteCommand);

        // Create devis with temporary num (0), the database will auto-generate it
        var devis = Devis.CreateDevis
        (
        num: 0, // Will be auto-generated by database
        idClient: createPriceQuoteCommand.IdClient,
        date: createPriceQuoteCommand.Date,
        totHTva: createPriceQuoteCommand.TotHTva,
        totTva: createPriceQuoteCommand.TotTva,
        totTtc: createPriceQuoteCommand.TotTtc
        );

        _ = _context.Devis.Add(devis);
        
        // Save the devis first to get its Num (which is the primary key)
        await _context.SaveChangesAsync(cancellationToken);

        // Now create the lines with the saved devis's Num
        foreach (var quotationLine in createPriceQuoteCommand.QuotationLines)
        {
            var ligneDevis = new LigneDevis
            {
                RefProduit = quotationLine.RefProduit,
                DesignationLi = quotationLine.DesignationLi,
                QteLi = quotationLine.QteLi,
                PrixHt = quotationLine.PrixHt,
                Remise = quotationLine.Remise,
                TotHt = quotationLine.TotHt,
                Tva = quotationLine.Tva,
                TotTtc = quotationLine.TotTtc,
                DevisId = devis.Num,
                NumDevisNavigation = devis
            };

            devis.LigneDevis.Add(ligneDevis);
        }

        // Save the lines
        _ = await _context.SaveChangesAsync(cancellationToken);
        _logger.LogEntityCreatedSuccessfully(nameof(Devis), devis.Num);

        return devis.Num;
    }
}
