global using Microsoft.AspNetCore.Diagnostics;
global using Microsoft.AspNetCore.Mvc;
global using System.Net;
global using System.Text.Json;
global using TunNetCom.SilkRoadErp.Sales.Api.Infrastructure.Extensions;
global using TunNetCom.SilkRoadErp.Sales.Api.Infrastructure;
global using FluentValidation;
global using Carter;
global using Microsoft.EntityFrameworkCore;
global using MediatR;
global using Mapster;
global using TunNetCom.SilkRoadErp.Sales.Domain.Entites;
global using TunNetCom.SilkRoadErp.Sales.Api.Contracts.Client;
global using FluentValidation.Results;
global using Serilog.Events;
global using Serilog;
global using TunNetCom.SilkRoadErp.Sales.Api.Infrastructure.Utilities;
global using Newtonsoft.Json;
global using Microsoft.AspNetCore.Http;
global using TunNetCom.SilkRoadErp.Sales.Api.Infrastructure.Behaviors;
global using FluentResults;
global using ILogger = Microsoft.Extensions.Logging.ILogger;

