// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class AvoirFinancierFournisseursConfiguration : IEntityTypeConfiguration<AvoirFinancierFournisseurs>
    {
        public void Configure(EntityTypeBuilder<AvoirFinancierFournisseurs> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.AvoirFinancierFournisseurs");

            entity.HasIndex(e => e.Num).IsUnique();
            entity.Property(e => e.Date)
                .HasColumnType("datetime")
                .HasColumnName("date");
            entity.Property(e => e.TotTtc)
                .HasColumnType("decimal(18, 3)")
                .HasColumnName("tot_ttc");

            entity.HasOne(d => d.NumFactureFournisseurNavigation)
                .WithMany(p => p.AvoirFinancierFournisseurs)
                .HasForeignKey(d => d.NumFactureFournisseur)
                .HasPrincipalKey(p => p.Num)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_dbo.AvoirFinancierFournisseurs_dbo.FactureFournisseur_NumFactureFournisseur");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AvoirFinancierFournisseurs> entity);
    }
}
