// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class SousFamilleProduitConfiguration : IEntityTypeConfiguration<SousFamilleProduit>
    {
        public void Configure(EntityTypeBuilder<SousFamilleProduit> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.SousFamilleProduit");

            entity.ToTable("SousFamilleProduit");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("Id");

            entity.Property(e => e.Nom)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nom");

            entity.Property(e => e.FamilleProduitId)
                .HasColumnName("FamilleProduitId");

            entity.HasOne(d => d.FamilleProduit)
                .WithMany(p => p.SousFamilles)
                .HasForeignKey(d => d.FamilleProduitId)
                .OnDelete(DeleteBehavior.Restrict)
                .IsRequired()
                .HasConstraintName("FK_dbo.SousFamilleProduit_dbo.FamilleProduit_FamilleProduitId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SousFamilleProduit> entity);
    }
}



