global using Newtonsoft.Json;
global using System.Text.Json;
global using TunNetCom.SilkRoadErp.Sales.Contracts;
global using TunNetCom.SilkRoadErp.Sales.Contracts.Customers;
global using OneOf;
global using System.Net;
global using static TunNetCom.SilkRoadErp.Sales.WebApp.Services.CustomerService;
global using TunNetCom.SilkRoadErp.Sales.Contracts.Invoice;
global using TunNetCom.SilkRoadErp.Sales.WebApp.Helpers;
global using TunNetCom.SilkRoadErp.Sales.Contracts.Products;
