apiVersion: v1
kind: Service
metadata:
  name: silkroad-webapp-service
  namespace: silkroad-dev
spec:
  selector:
    app: silkroad-webapp
    version: green
  ports:
    - name: http
      port: 8080
      targetPort: 8080
