// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class BonDeReceptionConfiguration : IEntityTypeConfiguration<BonDeReception>
    {
        public void Configure(EntityTypeBuilder<BonDeReception> entity)
        {
            entity.HasKey(e => e.Num).HasName("PK_dbo.BonDeReception");

            entity.Property(e => e.Date)
            .HasColumnType("datetime")
            .HasColumnName("date");
            entity.Property(e => e.DateLivraison)
            .HasColumnType("datetime")
            .HasColumnName("date_livraison");
            entity.Property(e => e.IdFournisseur).HasColumnName("id_fournisseur");
            entity.Property(e => e.NumBonFournisseur).HasColumnName("Num_Bon_fournisseur");
            entity.Property(e => e.NumFactureFournisseur).HasColumnName("Num_Facture_fournisseur");

            entity.HasOne(d => d.IdFournisseurNavigation).WithMany(p => p.BonDeReception)
            .HasForeignKey(d => d.IdFournisseur)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_dbo.BonDeReception_dbo.Fournisseur_id_fournisseur");

            entity.HasOne(d => d.NumFactureFournisseurNavigation).WithMany(p => p.BonDeReception)
            .HasForeignKey(d => d.NumFactureFournisseur)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_dbo.BonDeReception_dbo.FactureFournisseur_Num_Facture_fournisseur");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<BonDeReception> entity);
    }
}
