// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class DevisConfiguration : IEntityTypeConfiguration<Devis>
    {
        public void Configure(EntityTypeBuilder<Devis> entity)
        {
            entity.HasKey(e => e.Num).HasName("PK_dbo.Devis");

            entity.Property(e => e.Date)
            .HasColumnType("datetime")
            .HasColumnName("date");
            entity.Property(e => e.IdClient).HasColumnName("id_client");
            entity.Property(e => e.TotHTva)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("tot_H_tva");
            entity.Property(e => e.TotTtc)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("tot_ttc");
            entity.Property(e => e.TotTva)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("tot_tva");

            entity.HasOne(d => d.IdClientNavigation).WithMany(p => p.Devis)
            .HasForeignKey(d => d.IdClient)
            .HasConstraintName("FK_dbo.Devis_dbo.Client_id_client");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Devis> entity);
    }
}
