using TunNetCom.SilkRoadErp.Sales.Domain.Entites;
using DomainCommandes = TunNetCom.SilkRoadErp.Sales.Domain.Entites.Commandes;

namespace TunNetCom.SilkRoadErp.Sales.Api.Features.Commandes.CreateOrder;

public class CreateOrderCommandHandler(
    SalesContext _context,
    ILogger<CreateOrderCommandHandler> _logger)
    : IRequestHandler<CreateOrderCommand, Result<int>>
{
    public async Task<Result<int>> Handle(CreateOrderCommand createOrderCommand, CancellationToken cancellationToken)
    {
        _logger.LogEntityCreated(nameof(DomainCommandes), createOrderCommand);

        // Create commande with temporary num (0), the database will auto-generate it
        var commande = DomainCommandes.CreateCommandes(
            num: 0, // Will be auto-generated by database
            fournisseurId: createOrderCommand.FournisseurId,
            date: createOrderCommand.Date
        );

        _ = _context.Commandes.Add(commande);
        
        // Save the commande first to get its Num (which is the primary key)
        await _context.SaveChangesAsync(cancellationToken);

        // Now create the lines with the saved commande's Num
        foreach (var orderLine in createOrderCommand.OrderLines)
        {
            var ligneCommande = new LigneCommandes
            {
                RefProduit = orderLine.RefProduit,
                DesignationLi = orderLine.DesignationLi,
                QteLi = orderLine.QteLi,
                PrixHt = orderLine.PrixHt,
                Remise = orderLine.Remise,
                TotHt = orderLine.TotHt,
                Tva = orderLine.Tva,
                TotTtc = orderLine.TotTtc,
                NumCommande = commande.Num,
                NumCommandeNavigation = commande
            };

            commande.LigneCommandes.Add(ligneCommande);
        }

        // Save the lines
        _ = await _context.SaveChangesAsync(cancellationToken);
        _logger.LogEntityCreatedSuccessfully(nameof(DomainCommandes), commande.Num);

        return commande.Num;
    }
}

