# ============================================================
# Deploy SilkRoad API & WebApp to Societe Nizar Kubernetes
# ============================================================
trigger: none
pr: none

pool:
  name: OnPremAgents
  demands:
    - Agent.Name -equals nizarVps

variables:
- group: silkroad-prod
- name: connectionString
  value: $(Connection_String_SteNizar)
- name: kubeNamespace
  value: silkroad-nizar
- name: deploymentApiName
  value: silkroad-api-societe
- name: deploymentWebappName
  value: silkroad-webapp-societe
- name: manifestPath
  value: deployments/k8s/societeNizar-deploy.yaml

stages:
- stage: Deploy
  displayName: Deploy to Societe Nizar Kubernetes
  jobs:
  - template: templates/deploy-k8s-job.yml
    parameters:
      kubeNamespace: $(kubeNamespace)
      deploymentApiName: $(deploymentApiName)
      deploymentWebappName: $(deploymentWebappName)
      manifestPath: $(manifestPath)
      stageDisplayName: Deploy to Societe Nizar Kubernetes
      dockerRepository: 'tunnetcom/silkroad'
      apiImageTag: 'api-1966'
      webappImageTag: 'webapp-1966'
      forceImagePullPatch: false
