// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class AccountingYear
{
    private AccountingYear()
    {
    }

    public static AccountingYear CreateAccountingYear(
        int year, 
        bool isActive,
        decimal? timbre = null,
        decimal? pourcentageFodec = null,
        decimal? vatRate0 = null,
        decimal? vatRate7 = null,
        decimal? vatRate13 = null,
        decimal? vatRate19 = null,
        double? pourcentageRetenu = null,
        decimal? vatAmount = null,
        decimal? seuilRetenueSource = null)
    {
        return new AccountingYear
        {
            Year = year,
            IsActive = isActive,
            Timbre = timbre,
            PourcentageFodec = pourcentageFodec,
            VatRate0 = vatRate0,
            VatRate7 = vatRate7,
            VatRate13 = vatRate13,
            VatRate19 = vatRate19,
            PourcentageRetenu = pourcentageRetenu,
            VatAmount = vatAmount,
            SeuilRetenueSource = seuilRetenueSource
        };
    }

    public void UpdateAccountingYear(
        int year, 
        bool isActive,
        decimal? timbre = null,
        decimal? pourcentageFodec = null,
        decimal? vatRate0 = null,
        decimal? vatRate7 = null,
        decimal? vatRate13 = null,
        decimal? vatRate19 = null,
        double? pourcentageRetenu = null,
        decimal? vatAmount = null,
        decimal? seuilRetenueSource = null)
    {
        this.Year = year;
        this.IsActive = isActive;
        
        // Ne mettre à jour que les valeurs qui sont explicitement fournies (non-null)
        // Cela permet de faire des mises à jour partielles sans vider les valeurs existantes
        if (timbre.HasValue)
            this.Timbre = timbre;
        if (pourcentageFodec.HasValue)
            this.PourcentageFodec = pourcentageFodec;
        if (vatRate0.HasValue)
            this.VatRate0 = vatRate0;
        if (vatRate7.HasValue)
            this.VatRate7 = vatRate7;
        if (vatRate13.HasValue)
            this.VatRate13 = vatRate13;
        if (vatRate19.HasValue)
            this.VatRate19 = vatRate19;
        if (pourcentageRetenu.HasValue)
            this.PourcentageRetenu = pourcentageRetenu;
        if (vatAmount.HasValue)
            this.VatAmount = vatAmount;
        if (seuilRetenueSource.HasValue)
            this.SeuilRetenueSource = seuilRetenueSource;
    }

    public void SetActive()
    {
        this.IsActive = true;
    }

    public void SetInactive()
    {
        this.IsActive = false;
    }

    public int Id { get; private set; }

    public int Year { get; private set; }

    public bool IsActive { get; private set; }

    public decimal? Timbre { get; private set; }

    public decimal? PourcentageFodec { get; private set; }

    public decimal? VatRate0 { get; private set; }

    public decimal? VatRate7 { get; private set; }

    public decimal? VatRate13 { get; private set; }

    public decimal? VatRate19 { get; private set; }

    public double? PourcentageRetenu { get; private set; }

    public decimal? VatAmount { get; private set; }

    public decimal? SeuilRetenueSource { get; private set; }

    public virtual ICollection<Facture> Facture { get; set; } = new List<Facture>();

    public virtual ICollection<FactureFournisseur> FactureFournisseur { get; set; } = new List<FactureFournisseur>();

    public virtual ICollection<BonDeLivraison> BonDeLivraison { get; set; } = new List<BonDeLivraison>();

    public virtual ICollection<BonDeReception> BonDeReception { get; set; } = new List<BonDeReception>();

    public virtual ICollection<Avoirs> Avoirs { get; set; } = new List<Avoirs>();

    public virtual ICollection<AvoirFournisseur> AvoirFournisseur { get; set; } = new List<AvoirFournisseur>();

    public virtual ICollection<FactureAvoirFournisseur> FactureAvoirFournisseur { get; set; } = new List<FactureAvoirFournisseur>();

    public virtual ICollection<FactureAvoirClient> FactureAvoirClient { get; set; } = new List<FactureAvoirClient>();

    public virtual ICollection<Inventaire> Inventaires { get; set; } = new List<Inventaire>();
}

