// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class AccountingYear
{
    private AccountingYear()
    {
    }

    public static AccountingYear CreateAccountingYear(int year, bool isActive)
    {
        return new AccountingYear
        {
            Year = year,
            IsActive = isActive
        };
    }

    public void UpdateAccountingYear(int year, bool isActive)
    {
        this.Year = year;
        this.IsActive = isActive;
    }

    public void SetActive()
    {
        this.IsActive = true;
    }

    public void SetInactive()
    {
        this.IsActive = false;
    }

    public int Id { get; private set; }

    public int Year { get; private set; }

    public bool IsActive { get; private set; }

    public virtual ICollection<Facture> Facture { get; set; } = new List<Facture>();

    public virtual ICollection<FactureFournisseur> FactureFournisseur { get; set; } = new List<FactureFournisseur>();

    public virtual ICollection<BonDeLivraison> BonDeLivraison { get; set; } = new List<BonDeLivraison>();

    public virtual ICollection<BonDeReception> BonDeReception { get; set; } = new List<BonDeReception>();
}

