// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class AvoirFinancierFournisseurs
{
    public int Id { get; set; }

    public int Num { get; set; }

    public int? NumFactureFournisseur { get; set; }

    public int NumSurPage { get; set; }

    public DateTime Date { get; set; }

    public string? Description { get; set; }

    public decimal TotTtc { get; set; }

    public virtual FactureFournisseur? NumFactureFournisseurNavigation { get; set; }
}