// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class AvoirFournisseur : IAccountingYearEntity
{
    public static AvoirFournisseur CreateAvoirFournisseur(
        DateTime date,
        int? fournisseurId,
        int? factureAvoirFournisseurId,
        int accountingYearId,
        int numAvoirChezFournisseur)
    {
        return new AvoirFournisseur
        {
            Date = date,
            FournisseurId = fournisseurId,
            FactureAvoirFournisseurId = factureAvoirFournisseurId,
            AccountingYearId = accountingYearId,
            NumAvoirChezFournisseur = numAvoirChezFournisseur,
            Statut = DocumentStatus.Draft
        };
    }

    public void Valider()
    {
        if (Statut != DocumentStatus.Draft)
        {
            throw new InvalidOperationException("Seul un document en brouillon peut être validé.");
        }
        Statut = DocumentStatus.Valid;
    }

    public void UpdateAvoirFournisseur(
        DateTime date,
        int? fournisseurId,
        int? factureAvoirFournisseurId,
        int accountingYearId,
        int numAvoirChezFournisseur)
    {
        this.Date = date;
        this.FournisseurId = fournisseurId;
        this.FactureAvoirFournisseurId = factureAvoirFournisseurId;
        this.AccountingYearId = accountingYearId;
        this.NumAvoirChezFournisseur = numAvoirChezFournisseur;
    }

    public int Id { get; set; }

    public DateTime Date { get; set; }

    public int? FournisseurId { get; set; }

    public int? FactureAvoirFournisseurId { get; set; }

    public int NumAvoirChezFournisseur { get; set; }

    public int AccountingYearId { get; set; }

    public DocumentStatus Statut { get; private set; }

    public virtual Fournisseur? Fournisseur { get; set; }

    public virtual AccountingYear AccountingYear { get; set; } = null!;

    public virtual ICollection<LigneAvoirFournisseur> LigneAvoirFournisseur { get; set; } = new List<LigneAvoirFournisseur>();

    public virtual FactureAvoirFournisseur? FactureAvoirFournisseur { get; set; }
}