// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Avoirs : IAccountingYearEntity
{
    public static Avoirs CreateAvoir(
        DateTime date,
        int? clientId,
        int accountingYearId,
        int? numFactureAvoirClient = null)
    {
        return new Avoirs
        {
            Date = date,
            ClientId = clientId,
            AccountingYearId = accountingYearId,
            NumFactureAvoirClient = numFactureAvoirClient,
            Statut = DocumentStatus.Brouillon
        };
    }

    public void Valider()
    {
        if (Statut != DocumentStatus.Brouillon)
        {
            throw new InvalidOperationException("Seul un document en brouillon peut être validé.");
        }
        Statut = DocumentStatus.Valide;
    }

    public void UpdateAvoir(
        DateTime date,
        int? clientId,
        int accountingYearId,
        int? numFactureAvoirClient = null)
    {
        this.Date = date;
        this.ClientId = clientId;
        this.AccountingYearId = accountingYearId;
        this.NumFactureAvoirClient = numFactureAvoirClient;
    }

    public int Id { get; set; }

    public int Num { get; set; }

    public DateTime Date { get; set; }

    public int? ClientId { get; set; }

    public int AccountingYearId { get; set; }

    public int? NumFactureAvoirClient { get; set; }

    public DocumentStatus Statut { get; private set; }

    public virtual Client? Client { get; set; }

    public virtual AccountingYear AccountingYear { get; set; } = null!;

    public virtual ICollection<LigneAvoirs> LigneAvoirs { get; set; } = new List<LigneAvoirs>();

    public virtual FactureAvoirClient? NumFactureAvoirClientNavigation { get; set; }
}