// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class BonDeLivraison : IAccountingYearEntity
{
    public static BonDeLivraison CreateBonDeLivraison(
        DateTime date,
        decimal totHTva,
        decimal totTva,
        decimal netPayer,
        TimeOnly tempBl,
        int? numFacture,
        int? clientId,
        int accountingYearId,
        int? installationTechnicianId = null)
    {
        return new BonDeLivraison
        {
            Date = date,
            TotHTva = totHTva,
            TotTva = totTva,
            NetPayer = netPayer,
            TempBl = tempBl,
            NumFacture = numFacture,
            ClientId = clientId,
            AccountingYearId = accountingYearId,
            InstallationTechnicianId = installationTechnicianId,
            Statut = DocumentStatus.Draft
        };
    }

    public void Valider()
    {
        if (Statut != DocumentStatus.Draft)
        {
            throw new InvalidOperationException("Seul un document en brouillon peut être validé.");
        }
        Statut = DocumentStatus.Valid;
    }

    public void UpdateBonDeLivraison(
        DateTime date,
        decimal totHTva,
        decimal totTva,
        decimal netPayer,
        TimeOnly tempBl,
        int? numFacture,
        int? clientId,
        int accountingYearId,
        int? installationTechnicianId = null,
        int? deliveryCarId = null) 
    {
        this.Date = date;
        this.TotHTva = totHTva;
        this.TotTva = totTva;
        this.NetPayer = netPayer;
        this.TempBl = tempBl;
        this.NumFacture = numFacture;
        this.ClientId = clientId;
        this.AccountingYearId = accountingYearId;
        this.InstallationTechnicianId = installationTechnicianId;
        this.DeliveryCarId = deliveryCarId;
    }

    public int Id { get; set; }

    public int Num { get; set; }

    public DateTime Date { get; set; }

    public decimal TotHTva { get; set; }

    public decimal TotTva { get; set; }

    public decimal NetPayer { get; set; }

    public TimeOnly TempBl { get; set; }

    public int? NumFacture { get; set; }

    public int? ClientId { get; set; }

    public int AccountingYearId { get; set; }

    public int? InstallationTechnicianId { get; set; }

    public int? DeliveryCarId { get; set; }

    public DocumentStatus Statut { get; private set; }

    public virtual Client? Client { get; set; }

    public virtual InstallationTechnician? InstallationTechnician { get; set; }

    public virtual DeliveryCar? DeliveryCar { get; set; }

    public virtual ICollection<LigneBl> LigneBl { get; set; } = new List<LigneBl>();

    public virtual Facture? NumFactureNavigation { get; set; }

    public virtual Transaction? Transaction { get; set; }

    public virtual AccountingYear AccountingYear { get; set; } = null!;
}