// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class BonDeReception
{
        public void UpdateReceiptNote(
            int num,
            long numBonFournisseur,
            DateTime dateLivraison,
            int idFournisseur,
            DateTime date,
            int? numFactureFournisseur,
            int accountingYearId
        )
        {
            this.Num = num;
            this.NumBonFournisseur = numBonFournisseur;
            this.DateLivraison = dateLivraison;
            this.IdFournisseur = idFournisseur;
            this.Date = date;
            this.NumFactureFournisseur = numFactureFournisseur;
            this.AccountingYearId = accountingYearId;
        }

        public static BonDeReception CreateReceiptNote(
        int num,
        long numBonFournisseur,
        DateTime dateLivraison,
        int idFournisseur,
        DateTime date,
        int? numFactureFournisseur,
        int accountingYearId
        )
    {
        return new BonDeReception
        {
            Num = num,
            NumBonFournisseur = numBonFournisseur,
            DateLivraison = dateLivraison,
            IdFournisseur= idFournisseur,
            Date = date,
            NumFactureFournisseur= numFactureFournisseur,
            AccountingYearId = accountingYearId
        };
    }
    public int Id { get; set; }

    public int Num { get; set; }

    public long NumBonFournisseur { get; set; }

    public DateTime DateLivraison { get; set; }

    public int IdFournisseur { get; set; }

    public DateTime Date { get; set; }

    public int? NumFactureFournisseur { get; set; }

    public int AccountingYearId { get; set; }

    public virtual Fournisseur IdFournisseurNavigation { get; set; } = null!;

    public virtual ICollection<LigneBonReception> LigneBonReception { get; set; } = new List<LigneBonReception>();

    public virtual FactureFournisseur? NumFactureFournisseurNavigation { get; set; }

    public virtual AccountingYear AccountingYear { get; set; } = null!;
}