// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Client 
{
    public void UpdateClient(
        string nom,
        string? tel,
        string? adresse,
        string? matricule,
        string? code,
        string? codeCat,
        string? etbSec,
        string? mail)
    {
        this.Nom = nom;
        this.Tel = tel;
        this.Adresse = adresse;
        this.Matricule = matricule;
        this.Code = code;
        this.CodeCat = codeCat;
        this.EtbSec = etbSec;
        this.Mail = mail;
    }

    public static Client CreateClient(
        string nom,
        string? tel,
        string? adresse,
        string? matricule,
        string? code,
        string? codeCat,
        string? etbSec,
        string? mail)
    {
        return new Client
        {
            Nom = nom,
            Tel = tel,
            Adresse = adresse,
            Matricule = matricule,
            Code = code,
            CodeCat = codeCat,
            EtbSec = etbSec,
            Mail = mail
        };
    }

    public void SetId(int id)
    {
        this.Id = id;
    }

    public int Id { get; private set ; }

    public string Nom { get; private set ; } = null!;

    public string? Tel { get; private set; }

    public string? Adresse { get; private set; }

    public string? Matricule { get; private set; }

    public string? Code { get; private set; }

    public string? CodeCat { get; private set; }

    public string? EtbSec { get; private set; }

    public string? Mail { get; private set; }

    public virtual ICollection<Avoirs> Avoirs { get; set; } = new List<Avoirs>();

    public virtual ICollection<BonDeLivraison> BonDeLivraison { get; set; } = new List<BonDeLivraison>();

    public virtual ICollection<Devis> Devis { get; set; } = new List<Devis>();

    public virtual ICollection<Facture> Facture { get; set; } = new List<Facture>();
}