// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Commandes
{
    public int Num { get; set; }

    public DateTime Date { get; set; }

    public int? FournisseurId { get; set; }

    public virtual Fournisseur? Fournisseur { get; set; }

    public virtual ICollection<LigneCommandes> LigneCommandes { get; set; } = new List<LigneCommandes>();
}