// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Commandes
{
    public void UpdateCommandes(
        int num,
        int? fournisseurId,
        DateTime date)
    {
        this.Num = num;
        this.FournisseurId = fournisseurId;
        this.Date = date;
    }

    public static Commandes CreateCommandes(
        int num,
        int? fournisseurId,
        DateTime date)
    {
        return new Commandes
        {
            Num = num,
            FournisseurId = fournisseurId,
            Date = date,
            Statut = DocumentStatus.Draft
        };
    }

    public void Valider()
    {
        if (Statut != DocumentStatus.Draft)
        {
            throw new InvalidOperationException("Seul un document en brouillon peut être validé.");
        }
        Statut = DocumentStatus.Valid;
    }

    public int Num { get; set; }

    public DateTime Date { get; set; }

    public int? FournisseurId { get; set; }

    public DocumentStatus Statut { get; private set; }

    public virtual Fournisseur? Fournisseur { get; set; }

    public virtual ICollection<LigneCommandes> LigneCommandes { get; set; } = new List<LigneCommandes>();
}