// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class FactureFournisseur : IAccountingYearEntity
{
    public int Id { get; set; }

    public int Num { get; set; }

    public int IdFournisseur { get; set; }

    public bool Paye { get; set; }

    public long NumFactureFournisseur { get; set; }

    public DateTime DateFacturationFournisseur { get; set; }

    public DateTime Date { get; set; }

    public int AccountingYearId { get; set; }

    public DocumentStatus Statut { get; private set; }

    public void Valider()
    {
        if (Statut != DocumentStatus.Brouillon)
        {
            throw new InvalidOperationException("Seul un document en brouillon peut être validé.");
        }
        Statut = DocumentStatus.Valide;
    }

    public virtual AvoirFinancierFournisseurs? AvoirFinancierFournisseurs { get; set; }

    public virtual ICollection<BonDeReception> BonDeReception { get; set; } = new List<BonDeReception>();

    public virtual ICollection<FactureAvoirFournisseur> FactureAvoirFournisseur { get; set; } = new List<FactureAvoirFournisseur>();

    public virtual Fournisseur IdFournisseurNavigation { get; set; } = null!;

    public virtual AccountingYear AccountingYear { get; set; } = null!;
}