// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Facture
{
    public int Num { get; set; }

    public int IdClient { get; set; }

    public DateTime Date { get; set; }

    public virtual ICollection<BonDeLivraison> BonDeLivraison { get; set; } = new List<BonDeLivraison>();

    public virtual Client IdClientNavigation { get; set; } = null!;
}