// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class FamilleProduit
{
    private FamilleProduit()
    {
        
    }

    public void UpdateFamilleProduit(string nom)
    {
        this.Nom = nom;
    }

    public static FamilleProduit CreateFamilleProduit(string nom)
    {
        return new FamilleProduit
        {
            Nom = nom
        };
    }

    public void SetId(int id)
    {
        this.Id = id;
    }

    public int Id { get; private set; }

    public string Nom { get; private set; } = null!;

    public virtual ICollection<SousFamilleProduit> SousFamilles { get; set; } = new List<SousFamilleProduit>();
}



