// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Fournisseur
{
    public void UpdateProvider(
         string nom,
         string tel,
         string? fax,
         string? matricule,
         string? code,
         string? codeCat,
         string? etbSec,
         string? mail,
         string? mailDeux,
         bool constructeur,
         string? adresse)
    {
        this.Nom = nom;
        this.Tel = tel;
        this.Fax = fax;
        this.Matricule = matricule;
        this.Code = code;
        this.CodeCat = codeCat;
        this.EtbSec = etbSec;
        this.Mail = mail;
        this.MailDeux = mailDeux;
        this.Constructeur = constructeur;
        this.Adresse = adresse;
              }
    public static Fournisseur CreateProvider(
     string nom,
     string tel,
     string? fax,
     string? matricule,
     string? code,
     string? codeCat,
     string? etbSec,
     string? mail,
     string? mailDeux,
     bool constructeur,
     string? adresse)
    {
        return new Fournisseur
        {
            Nom = nom,
            Tel = tel,
            Fax = fax,
            Matricule = matricule,
            Code = code,
            CodeCat = codeCat,
            EtbSec = etbSec,
            Mail = mail,
            MailDeux = mailDeux,
            Constructeur = constructeur,
            Adresse = adresse
        };
    }


    public int Id { get; set; }

    public string Nom { get; set; } = null!;

    public string Tel { get; set; } = null!;

    public string? Fax { get; set; }

    public string? Matricule { get; set; }

    public string? Code { get; set; }

    public string? CodeCat { get; set; }

    public string? EtbSec { get; set; }

    public string? Mail { get; set; }

    public string? MailDeux { get; set; }

    public bool Constructeur { get; set; }

    public string? Adresse { get; set; }

    public virtual ICollection<AvoirFournisseur> AvoirFournisseur { get; set; } = new List<AvoirFournisseur>();

    public virtual ICollection<BonDeReception> BonDeReception { get; set; } = new List<BonDeReception>();

    public virtual ICollection<Commandes> Commandes { get; set; } = new List<Commandes>();

    public virtual ICollection<EcheanceDesFournisseurs> EcheanceDesFournisseurs { get; set; } = new List<EcheanceDesFournisseurs>();

    public virtual ICollection<FactureAvoirFournisseur> FactureAvoirFournisseur { get; set; } = new List<FactureAvoirFournisseur>();

    public virtual ICollection<FactureFournisseur> FactureFournisseur { get; set; } = new List<FactureFournisseur>();
}