// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class InstallationTechnician
{
    private InstallationTechnician()
    {
        
    }

    public void UpdateInstallationTechnician(
        string nom,
        string? tel,
        string? tel2,
        string? tel3,
        string? email,
        string? description,
        string? photo)
    {
        this.Nom = nom;
        this.Tel = tel;
        this.Tel2 = tel2;
        this.Tel3 = tel3;
        this.Email = email;
        this.Description = description;
        this.Photo = photo;
    }

    public static InstallationTechnician CreateInstallationTechnician(
        string nom,
        string? tel,
        string? tel2,
        string? tel3,
        string? email,
        string? description,
        string? photo)
    {
        return new InstallationTechnician
        {
            Nom = nom,
            Tel = tel,
            Tel2 = tel2,
            Tel3 = tel3,
            Email = email,
            Description = description,
            Photo = photo
        };
    }

    public void SetId(int id)
    {
        this.Id = id;
    }

    public int Id { get; private set; }

    public string Nom { get; private set; } = null!;

    public string? Tel { get; private set; }

    public string? Tel2 { get; private set; }

    public string? Tel3 { get; private set; }

    public string? Email { get; private set; }

    public string? Description { get; private set; }

    public string? Photo { get; private set; }

    public virtual ICollection<BonDeLivraison> BonDeLivraison { get; set; } = new List<BonDeLivraison>();
}

