// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class LigneBonReception
{
    public int IdLigne { get; set; }

    public int BonDeReceptionId { get; set; }

    public string RefProduit { get; set; } = null!;

    public string DesignationLi { get; set; } = null!;

    public int QteLi { get; set; }

    public decimal PrixHt { get; set; }

    public double Remise { get; set; }

    public decimal TotHt { get; set; }

    public double Tva { get; set; }

    public decimal TotTtc { get; set; }

    public virtual BonDeReception NumBonRecNavigation { get; set; } = null!;

    public virtual Produit RefProduitNavigation { get; set; } = null!;

    public static LigneBonReception CreateReceiptNoteLine(
        int bonDeReceptionId,
        string productRef,
        string designationLigne,
        int quantity,
        decimal unitPrice,
        double discount,
        double tax)
    {
        var subtotalBeforeDiscount = quantity * unitPrice;
        var discountAmount = subtotalBeforeDiscount * (decimal)(discount / 100);
        var subtotalAfterDiscount = subtotalBeforeDiscount - discountAmount;
        
        return new LigneBonReception
        {
            RefProduit = productRef,
            DesignationLi = designationLigne,
            QteLi = quantity,
            PrixHt = unitPrice,
            Remise = discount,
            TotHt = subtotalAfterDiscount,
            Tva = tax,
            TotTtc = subtotalAfterDiscount * (1 + (decimal)(tax / 100)),
            BonDeReceptionId = bonDeReceptionId
        };
    }
}