// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations;
#nullable enable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class SalesContext : DbContext
{
    // Variable AsyncLocal pour stocker l'ID de l'exercice actif de manière thread-safe avec async/await
    // Cette valeur sera mise à jour par le middleware au début de chaque requête HTTP
    private static readonly AsyncLocal<int?> _activeAccountingYearId = new();

    public static void SetActiveAccountingYearId(int? yearId)
    {
        _activeAccountingYearId.Value = yearId;
    }

    public static int? GetActiveAccountingYearId()
    {
        return _activeAccountingYearId.Value;
    }

    public SalesContext(DbContextOptions<SalesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AvoirFinancierFournisseurs> AvoirFinancierFournisseurs { get; set; }

    public virtual DbSet<AvoirFournisseur> AvoirFournisseur { get; set; }

    public virtual DbSet<Avoirs> Avoirs { get; set; }

    public virtual DbSet<AccountingYear> AccountingYear { get; set; }

    public virtual DbSet<BonDeLivraison> BonDeLivraison { get; set; }

    public virtual DbSet<BonDeReception> BonDeReception { get; set; }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Commandes> Commandes { get; set; }

    public virtual DbSet<Devis> Devis { get; set; }

    public virtual DbSet<EcheanceDesFournisseurs> EcheanceDesFournisseurs { get; set; }

    public virtual DbSet<Facture> Facture { get; set; }

    public virtual DbSet<FactureAvoirClient> FactureAvoirClient { get; set; }

    public virtual DbSet<FactureAvoirFournisseur> FactureAvoirFournisseur { get; set; }

    public virtual DbSet<FactureFournisseur> FactureFournisseur { get; set; }

    public virtual DbSet<Fournisseur> Fournisseur { get; set; }

    public virtual DbSet<LigneAvoirFournisseur> LigneAvoirFournisseur { get; set; }

    public virtual DbSet<LigneAvoirs> LigneAvoirs { get; set; }

    public virtual DbSet<LigneBl> LigneBl { get; set; }

    public virtual DbSet<LigneBonReception> LigneBonReception { get; set; }

    public virtual DbSet<RetourMarchandiseFournisseur> RetourMarchandiseFournisseur { get; set; }

    public virtual DbSet<LigneRetourMarchandiseFournisseur> LigneRetourMarchandiseFournisseur { get; set; }

    public virtual DbSet<ReceptionRetourFournisseur> ReceptionRetourFournisseur { get; set; }

    public virtual DbSet<LigneCommandes> LigneCommandes { get; set; }

    public virtual DbSet<LigneDevis> LigneDevis { get; set; }

    public virtual DbSet<Inventaire> Inventaire { get; set; }

    public virtual DbSet<LigneInventaire> LigneInventaire { get; set; }

    public virtual DbSet<Produit> Produit { get; set; }

    public virtual DbSet<FamilleProduit> FamilleProduit { get; set; }

    public virtual DbSet<SousFamilleProduit> SousFamilleProduit { get; set; }

    public virtual DbSet<Systeme> Systeme { get; set; }

    public virtual DbSet<Transaction> Transaction { get; set; }


    public virtual DbSet<Banque> Banque { get; set; }

    public virtual DbSet<CompteBancaire> CompteBancaire { get; set; }

    public virtual DbSet<BankTransactionImport> BankTransactionImport { get; set; }

    public virtual DbSet<BankTransaction> BankTransaction { get; set; }

    public virtual DbSet<PaiementClient> PaiementClient { get; set; }

    public virtual DbSet<PaiementFournisseur> PaiementFournisseur { get; set; }

    public virtual DbSet<Tag> Tag { get; set; }

    public virtual DbSet<DocumentTag> DocumentTag { get; set; }

    public virtual DbSet<InstallationTechnician> InstallationTechnician { get; set; }

    public virtual DbSet<DeliveryCar> DeliveryCar { get; set; }

    public virtual DbSet<User> User { get; set; }

    public virtual DbSet<Role> Role { get; set; }

    public virtual DbSet<Permission> Permission { get; set; }

    public virtual DbSet<UserRole> UserRole { get; set; }

    public virtual DbSet<RolePermission> RolePermission { get; set; }

    public virtual DbSet<RefreshToken> RefreshToken { get; set; }

    public virtual DbSet<AuditLog> AuditLog { get; set; }

    public virtual DbSet<PrintHistory> PrintHistory { get; set; }

    public virtual DbSet<RetenueSourceClient> RetenueSourceClient { get; set; }

    public virtual DbSet<RetenueSourceFournisseur> RetenueSourceFournisseur { get; set; }

    public virtual DbSet<TejCertificatSequence> TejCertificatSequence { get; set; }

    public virtual DbSet<TejCertificatFacture> TejCertificatFacture { get; set; }

    public virtual DbSet<TejCertificatFactureDepense> TejCertificatFactureDepense { get; set; }

    public virtual DbSet<Notification> Notification { get; set; }

    public virtual DbSet<TiersDepenseFonctionnement> TiersDepenseFonctionnement { get; set; }

    public virtual DbSet<FactureDepense> FactureDepense { get; set; }

    public virtual DbSet<PaiementTiersDepense> PaiementTiersDepense { get; set; }

    public virtual DbSet<PaiementTiersDepenseFactureDepense> PaiementTiersDepenseFactureDepense { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(FactureConfiguration).Assembly);

        // Désactivé : Les Global Query Filters ne peuvent pas utiliser des appels de méthode non traduisibles en SQL
        // On utilise maintenant l'extension method FilterByActiveAccountingYear() dans les requêtes
        // ConfigureAccountingYearFilters(modelBuilder);

        OnModelCreatingPartial(modelBuilder);
    }

    private void ConfigureAccountingYearFilters(ModelBuilder modelBuilder)
    {
        // Cette méthode est désactivée car les Global Query Filters ne peuvent pas utiliser des appels de méthode non traduisibles en SQL
        // On utilise maintenant l'extension method FilterByActiveAccountingYear() dans les requêtes
        // Les entités qui implémentent IAccountingYearEntity doivent utiliser .FilterByActiveAccountingYear() dans leurs requêtes
    }

    private LambdaExpression CreateAccountingYearFilterExpression(Type entityType)
    {
        var parameter = Expression.Parameter(entityType, "e");
        var property = Expression.Property(parameter, nameof(IAccountingYearEntity.AccountingYearId));
        
        // Utiliser la variable statique thread-safe pour obtenir l'ID de l'exercice actif
        // Cette valeur sera mise à jour par le middleware au début de chaque requête HTTP
        // EF Core ne peut pas traduire cet appel de méthode en SQL, mais il peut évaluer l'expression
        // à chaque requête si on utilise une expression qui appelle la méthode
        var getActiveYearIdMethod = typeof(SalesContext).GetMethod(
            nameof(GetActiveAccountingYearId),
            BindingFlags.Public | BindingFlags.Static)!;
        
        var methodCall = Expression.Call(getActiveYearIdMethod);
        
        // Créer une expression qui compare AccountingYearId avec la valeur retournée par GetActiveAccountingYearId()
        // Si la valeur est null, on retourne false (pas de résultats) pour forcer le filtre à exclure toutes les entités
        // Sinon, on compare AccountingYearId avec la valeur de l'AsyncLocal
        // Note: EF Core ne peut pas traduire cet appel de méthode en SQL, donc on doit utiliser
        // un interceptor qui modifie la requête SQL directement, ou utiliser une approche différente
        var nullCheck = Expression.Condition(
            Expression.Equal(methodCall, Expression.Constant(null, typeof(int?))),
            Expression.Constant(false), // Si null, retourner false (exclure toutes les entités)
            Expression.Equal(property, Expression.Property(methodCall, "Value"))); // Sinon, comparer avec la valeur
        
        return Expression.Lambda(nullCheck, parameter);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
