// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations;
#nullable enable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class SalesContext : DbContext
{
    public SalesContext(DbContextOptions<SalesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AvoirFinancierFournisseurs> AvoirFinancierFournisseurs { get; set; }

    public virtual DbSet<AvoirFournisseur> AvoirFournisseur { get; set; }

    public virtual DbSet<Avoirs> Avoirs { get; set; }

    public virtual DbSet<BonDeLivraison> BonDeLivraison { get; set; }

    public virtual DbSet<BonDeReception> BonDeReception { get; set; }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Commandes> Commandes { get; set; }

    public virtual DbSet<Devis> Devis { get; set; }

    public virtual DbSet<EcheanceDesFournisseurs> EcheanceDesFournisseurs { get; set; }

    public virtual DbSet<Facture> Facture { get; set; }

    public virtual DbSet<FactureAvoirFournisseur> FactureAvoirFournisseur { get; set; }

    public virtual DbSet<FactureFournisseur> FactureFournisseur { get; set; }

    public virtual DbSet<Fournisseur> Fournisseur { get; set; }

    public virtual DbSet<LigneAvoirFournisseur> LigneAvoirFournisseur { get; set; }

    public virtual DbSet<LigneAvoirs> LigneAvoirs { get; set; }

    public virtual DbSet<LigneBl> LigneBl { get; set; }

    public virtual DbSet<LigneBonReception> LigneBonReception { get; set; }

    public virtual DbSet<LigneCommandes> LigneCommandes { get; set; }

    public virtual DbSet<LigneDevis> LigneDevis { get; set; }

    public virtual DbSet<Produit> Produit { get; set; }

    public virtual DbSet<Systeme> Systeme { get; set; }

    public virtual DbSet<Transaction> Transaction { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(FactureConfiguration).Assembly);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
