// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class SousFamilleProduit
{
    private SousFamilleProduit()
    {
        
    }

    public void UpdateSousFamilleProduit(string nom, int familleProduitId)
    {
        this.Nom = nom;
        this.FamilleProduitId = familleProduitId;
    }

    public static SousFamilleProduit CreateSousFamilleProduit(string nom, int familleProduitId)
    {
        return new SousFamilleProduit
        {
            Nom = nom,
            FamilleProduitId = familleProduitId
        };
    }

    public void SetId(int id)
    {
        this.Id = id;
    }

    public int Id { get; private set; }

    public string Nom { get; private set; } = null!;

    public int FamilleProduitId { get; private set; }

    public virtual FamilleProduit FamilleProduit { get; set; } = null!;

    public virtual ICollection<Produit> Produits { get; set; } = new List<Produit>();
}



