// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Systeme
{

    public void UpdateSysteme(
        string nomSociete,
        decimal timbre,
        string adresse,
        string tel,
        string? fax,
        string? email,
        string? matriculeFiscale,
        string codeTva,
        string? codeCategorie,
        string? etbSecondaire,
        decimal pourcentageFodec,
        string? adresseRetenu,
        double pourcentageRetenu,
        decimal vatAmount,
        decimal discountPercentage,
        decimal vatRate0,
        decimal vatRate7,
        decimal vatRate13,
        decimal vatRate19,
        bool bloquerVenteStockInsuffisant)
    {
        this.NomSociete = nomSociete;
        this.Timbre = timbre;
        this.Adresse = adresse;
        this.Tel = tel;
        this.Fax = fax;
        this.Email = email;
        this.MatriculeFiscale = matriculeFiscale;
        this.CodeTva = codeTva;
        this.CodeCategorie = codeCategorie;
        this.EtbSecondaire = etbSecondaire;
        this.PourcentageFodec = pourcentageFodec;
        this.AdresseRetenu = adresseRetenu;
        this.PourcentageRetenu = pourcentageRetenu;
        this.VatAmount = vatAmount;
        this.DiscountPercentage = discountPercentage;
        this.VatRate0 = vatRate0;
        this.VatRate7 = vatRate7;
        this.VatRate13 = vatRate13;
        this.VatRate19 = vatRate19;
        this.BloquerVenteStockInsuffisant = bloquerVenteStockInsuffisant;
    }
    public int Id { get; set; }

    public string NomSociete { get; set; } = null!;

    public decimal Timbre { get; set; }

    public string Adresse { get; set; } = null!;

    public string Tel { get; set; } = null!;

    public string? Fax { get; set; }

    public string? Email { get; set; }

    public string? MatriculeFiscale { get; set; }

    public string CodeTva { get; set; } = null!;

    public string? CodeCategorie { get; set; }

    public string? EtbSecondaire { get; set; }

    public decimal PourcentageFodec { get; set; }

    public string? AdresseRetenu { get; set; }

    public double PourcentageRetenu { get; set; }

    public decimal DiscountPercentage { get; set; }

    public decimal VatAmount { get; set; }

    public decimal VatRate0 { get; set; }

    public decimal VatRate7 { get; set; }

    public decimal VatRate13 { get; set; }

    public decimal VatRate19 { get; set; }

    public bool BloquerVenteStockInsuffisant { get; set; }

}