// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Systeme
{

    public void UpdateSysteme(
        string nomSociete,
        string adresse,
        string tel,
        string? fax,
        string? email,
        string? matriculeFiscale,
        string codeTva,
        string? codeCategorie,
        string? etbSecondaire,
        string? adresseRetenu,
        decimal discountPercentage,
        bool bloquerVenteStockInsuffisant,
        bool bloquerBlSansFacture,
        int decimalPlaces,
        string? rib,
        string? ribCodeEtab,
        string? ribCodeAgence,
        string? ribNumeroCompte,
        string? ribCle,
        string? banqueEntreprise)
    {
        this.NomSociete = nomSociete;
        this.Adresse = adresse;
        this.Tel = tel;
        this.Fax = fax;
        this.Email = email;
        this.MatriculeFiscale = matriculeFiscale;
        this.CodeTva = codeTva;
        this.CodeCategorie = codeCategorie;
        this.EtbSecondaire = etbSecondaire;
        this.AdresseRetenu = adresseRetenu;
        this.DiscountPercentage = discountPercentage;
        this.BloquerVenteStockInsuffisant = bloquerVenteStockInsuffisant;
        this.BloquerBlSansFacture = bloquerBlSansFacture;
        this.DecimalPlaces = decimalPlaces;
        this.Rib = rib;
        this.RibCodeEtab = ribCodeEtab;
        this.RibCodeAgence = ribCodeAgence;
        this.RibNumeroCompte = ribNumeroCompte;
        this.RibCle = ribCle;
        this.BanqueEntreprise = banqueEntreprise;
    }
    public int Id { get; set; }

    public string NomSociete { get; set; } = null!;

    public string Adresse { get; set; } = null!;

    public string Tel { get; set; } = null!;

    public string? Fax { get; set; }

    public string? Email { get; set; }

    public string? MatriculeFiscale { get; set; }

    public string CodeTva { get; set; } = null!;

    public string? CodeCategorie { get; set; }

    public string? EtbSecondaire { get; set; }

    public string? AdresseRetenu { get; set; }

    public decimal DiscountPercentage { get; set; }

    public bool BloquerVenteStockInsuffisant { get; set; }

    public bool BloquerBlSansFacture { get; set; }

    // Default value for database - matches DecimalFormatConstants.DEFAULT_DECIMAL_PLACES in Contracts
    public int DecimalPlaces { get; set; } = 3;

    public string? Rib { get; set; }

    public string? RibCodeEtab { get; set; }

    public string? RibCodeAgence { get; set; }

    public string? RibNumeroCompte { get; set; }

    public string? RibCle { get; set; }

    public string? BanqueEntreprise { get; set; }

}