// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Devis
{
    public int Num { get; set; }

    public int IdClient { get; set; }

    public DateTime Date { get; set; }

    public decimal TotHTva { get; set; }

    public decimal TotTva { get; set; }

    public decimal TotTtc { get; set; }

    public virtual Client IdClientNavigation { get; set; } = null!;

    public virtual ICollection<LigneDevis> LigneDevis { get; set; } = new List<LigneDevis>();
}