// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class EcheanceDesFournisseurs
{
    public int Id { get; set; }

    public DateTime DateEcheance { get; set; }

    public long NumCheque { get; set; }

    public decimal Montant { get; set; }

    public int FournisseurId { get; set; }

    public virtual Fournisseur Fournisseur { get; set; } = null!;
}