// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class FactureAvoirFournisseur
{
    public int Num { get; set; }

    public int NumFactureAvoirFourSurPage { get; set; }

    public int IdFournisseur { get; set; }

    public DateTime Date { get; set; }

    public int? NumFactureFournisseur { get; set; }

    public virtual ICollection<AvoirFournisseur> AvoirFournisseur { get; set; } = new List<AvoirFournisseur>();

    public virtual Fournisseur IdFournisseurNavigation { get; set; } = null!;

    public virtual FactureFournisseur? NumFactureFournisseurNavigation { get; set; }
}