// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations;
#nullable enable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class SalesContext : DbContext
{
    public SalesContext(DbContextOptions<SalesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AvoirFinancierFournisseurs> AvoirFinancierFournisseurs { get; set; }

    public virtual DbSet<AvoirFournisseur> AvoirFournisseur { get; set; }

    public virtual DbSet<Avoirs> Avoirs { get; set; }

    public virtual DbSet<BonDeLivraison> BonDeLivraison { get; set; }

    public virtual DbSet<BonDeReception> BonDeReception { get; set; }

    public virtual DbSet<Client> Client { get; set; }

    public virtual DbSet<Commandes> Commandes { get; set; }

    public virtual DbSet<Devis> Devis { get; set; }

    public virtual DbSet<EcheanceDesFournisseurs> EcheanceDesFournisseurs { get; set; }

    public virtual DbSet<Facture> Facture { get; set; }

    public virtual DbSet<FactureAvoirFournisseur> FactureAvoirFournisseur { get; set; }

    public virtual DbSet<FactureFournisseur> FactureFournisseur { get; set; }

    public virtual DbSet<Fournisseur> Fournisseur { get; set; }

    public virtual DbSet<LigneAvoirFournisseur> LigneAvoirFournisseur { get; set; }

    public virtual DbSet<LigneAvoirs> LigneAvoirs { get; set; }

    public virtual DbSet<LigneBl> LigneBl { get; set; }

    public virtual DbSet<LigneBonReception> LigneBonReception { get; set; }

    public virtual DbSet<LigneCommandes> LigneCommandes { get; set; }

    public virtual DbSet<LigneDevis> LigneDevis { get; set; }

    public virtual DbSet<Produit> Produit { get; set; }

    public virtual DbSet<Systeme> Systeme { get; set; }

    public virtual DbSet<Transaction> Transaction { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.AvoirFinancierFournisseursConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AvoirFournisseurConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.AvoirsConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BonDeLivraisonConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.BonDeReceptionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ClientConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.CommandesConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.DevisConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EcheanceDesFournisseursConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FactureConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FactureAvoirFournisseurConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FactureFournisseurConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.FournisseurConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LigneAvoirFournisseurConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LigneAvoirsConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LigneBlConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LigneBonReceptionConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LigneCommandesConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.LigneDevisConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.ProduitConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.SystemeConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.TransactionConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
