// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Systeme
{
    public int Id { get; set; }

    public string NomSociete { get; set; } = null!;

    public decimal Timbre { get; set; }

    public string Adresse { get; set; } = null!;

    public string Tel { get; set; } = null!;

    public string? Fax { get; set; }

    public string? Email { get; set; }

    public string? MatriculeFiscale { get; set; }

    public string CodeTva { get; set; } = null!;

    public string? CodeCategorie { get; set; }

    public string? EtbSecondaire { get; set; }

    public decimal PourcentageFodec { get; set; }

    public string? AdresseRetenu { get; set; }

    public double PourcentageRetenu { get; set; }
}