// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites;

public partial class Transaction
{
    public int NumBl { get; set; }

    public int Type { get; set; }

    public DateTime DateTr { get; set; }

    public decimal Montant { get; set; }

    public virtual BonDeLivraison NumBlNavigation { get; set; } = null!;
}