// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations;

public partial class AccountingYearConfiguration : IEntityTypeConfiguration<AccountingYear>
{
    public void Configure(EntityTypeBuilder<AccountingYear> entity)
    {
        entity.ToTable("AccountingYear");

        entity.HasKey(e => e.Id);

        entity.Property(e => e.Id)
            .HasColumnName("Id")
            .ValueGeneratedOnAdd();

        entity.Property(e => e.Year)
            .HasColumnName("Year")
            .IsRequired();

        entity.Property(e => e.IsActive)
            .HasColumnName("IsActive")
            .IsRequired()
            .HasDefaultValue(false);

        entity.Property(e => e.Timbre)
            .HasColumnName("Timbre")
            .HasColumnType("decimal(18, 3)");

        entity.Property(e => e.PourcentageFodec)
            .HasColumnName("PourcentageFodec")
            .HasColumnType("decimal(18, 2)");

        entity.Property(e => e.VatRate0)
            .HasColumnName("VatRate0")
            .HasColumnType("decimal(18, 2)");

        entity.Property(e => e.VatRate7)
            .HasColumnName("VatRate7")
            .HasColumnType("decimal(18, 2)");

        entity.Property(e => e.VatRate13)
            .HasColumnName("VatRate13")
            .HasColumnType("decimal(18, 2)");

        entity.Property(e => e.VatRate19)
            .HasColumnName("VatRate19")
            .HasColumnType("decimal(18, 2)");

        entity.Property(e => e.PourcentageRetenu)
            .HasColumnName("PourcentageRetenu");

        entity.Property(e => e.VatAmount)
            .HasColumnName("VatAmount")
            .HasColumnType("decimal(18, 3)");

        entity.Property(e => e.SeuilRetenueSource)
            .HasColumnName("SeuilRetenueSource")
            .HasColumnType("decimal(18, 3)");

        // Contrainte unique sur Year (un seul exercice par année)
        entity.HasIndex(e => e.Year)
            .IsUnique()
            .HasDatabaseName("IX_AccountingYear_Year");
    }
}

