// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations;

public partial class AccountingYearConfiguration : IEntityTypeConfiguration<AccountingYear>
{
    public void Configure(EntityTypeBuilder<AccountingYear> entity)
    {
        entity.ToTable("AccountingYear");

        entity.HasKey(e => e.Id);

        entity.Property(e => e.Id)
            .HasColumnName("Id")
            .ValueGeneratedOnAdd();

        entity.Property(e => e.Year)
            .HasColumnName("Year")
            .IsRequired();

        entity.Property(e => e.IsActive)
            .HasColumnName("IsActive")
            .IsRequired()
            .HasDefaultValue(false);

        // Contrainte unique sur Year (un seul exercice par année)
        entity.HasIndex(e => e.Year)
            .IsUnique()
            .HasDatabaseName("IX_AccountingYear_Year");
    }
}

