// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class AvoirsConfiguration : IEntityTypeConfiguration<Avoirs>
    {
        public void Configure(EntityTypeBuilder<Avoirs> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.Avoirs");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd();

            entity.HasIndex(e => e.Num)
                .IsUnique()
                .HasDatabaseName("IX_Avoirs_Num");

            entity.Property(e => e.ClientId).HasColumnName("clientId");
            entity.Property(e => e.Date)
            .HasColumnType("datetime")
            .HasColumnName("date");
            entity.Property(e => e.NumFactureAvoirClient).HasColumnName("Num_FactureAvoirClient");
            entity.Property(e => e.Statut)
            .HasConversion<string>()
            .HasMaxLength(50)
            .IsRequired();

            entity.HasOne(d => d.Client).WithMany(p => p.Avoirs)
            .HasForeignKey(d => d.ClientId)
            .HasConstraintName("FK_dbo.Avoirs_dbo.Client_clientId");

            entity.HasOne(d => d.AccountingYear).WithMany(p => p.Avoirs)
            .HasForeignKey(d => d.AccountingYearId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_dbo.Avoirs_dbo.AccountingYear_AccountingYearId");

            entity.HasOne(d => d.NumFactureAvoirClientNavigation).WithMany(p => p.Avoirs)
            .HasForeignKey(d => d.NumFactureAvoirClient)
            .OnDelete(DeleteBehavior.NoAction)
            .HasConstraintName("FK_dbo.Avoirs_dbo.FactureAvoirClient_Num_FactureAvoirClient");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Avoirs> entity);
    }
}
