// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class AvoirFournisseurConfiguration : IEntityTypeConfiguration<AvoirFournisseur>
    {
        public void Configure(EntityTypeBuilder<AvoirFournisseur> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.AvoirFournisseur");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd();

            entity.HasIndex(e => e.Num)
                .IsUnique()
                .HasDatabaseName("IX_AvoirFournisseur_Num");

            entity.Property(e => e.Date)
            .HasColumnType("datetime")
            .HasColumnName("date");
            entity.Property(e => e.FournisseurId).HasColumnName("fournisseurId");
            entity.Property(e => e.NumAvoirFournisseur).HasColumnName("Num_AvoirFournisseur");
            entity.Property(e => e.NumFactureAvoirFournisseur).HasColumnName("Num_FactureAvoirFournisseur");
            entity.Property(e => e.Statut)
            .HasConversion<string>()
            .HasMaxLength(50)
            .IsRequired();

            entity.HasOne(d => d.Fournisseur).WithMany(p => p.AvoirFournisseur)
            .HasForeignKey(d => d.FournisseurId)
            .HasConstraintName("FK_dbo.AvoirFournisseur_dbo.Fournisseur_fournisseurId");

            entity.HasOne(d => d.NumFactureAvoirFournisseurNavigation).WithMany(p => p.AvoirFournisseur)
            .HasForeignKey(d => d.NumFactureAvoirFournisseur)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_dbo.AvoirFournisseur_dbo.FactureAvoirFournisseur_Num_FactureAvoirFournisseur");

            entity.HasOne(d => d.AccountingYear).WithMany(p => p.AvoirFournisseur)
            .HasForeignKey(d => d.AccountingYearId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_dbo.AvoirFournisseur_dbo.AccountingYear_AccountingYearId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AvoirFournisseur> entity);
    }
}
