// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class ClientConfiguration : IEntityTypeConfiguration<Client>
    {
        public void Configure(EntityTypeBuilder<Client> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.Client");

            entity.Property(e => e.Adresse)
            .HasMaxLength(50)
            .HasColumnName("adresse");
            entity.Property(e => e.Code).HasColumnName("code");
            entity.Property(e => e.CodeCat).HasColumnName("code_cat");
            entity.Property(e => e.EtbSec).HasColumnName("etb_sec");
            entity.Property(e => e.Mail).HasColumnName("mail");
            entity.Property(e => e.Matricule).HasColumnName("matricule");
            entity.Property(e => e.Nom)
            .HasMaxLength(50)
            .HasColumnName("nom");
            entity.Property(e => e.Tel)
            .HasMaxLength(50)
            .HasColumnName("tel");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Client> entity);
    }
}
