// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class CommandesConfiguration : IEntityTypeConfiguration<Commandes>
    {
        public void Configure(EntityTypeBuilder<Commandes> entity)
        {
            entity.HasKey(e => e.Num).HasName("PK_dbo.Commandes");

            entity.Property(e => e.Date)
            .HasColumnType("datetime")
            .HasColumnName("date");
            entity.Property(e => e.FournisseurId).HasColumnName("fournisseurId");

            entity.HasOne(d => d.Fournisseur).WithMany(p => p.Commandes)
            .HasForeignKey(d => d.FournisseurId)
            .HasConstraintName("FK_dbo.Commandes_dbo.Fournisseur_fournisseurId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Commandes> entity);
    }
}
