// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class EcheanceDesFournisseursConfiguration : IEntityTypeConfiguration<EcheanceDesFournisseurs>
    {
        public void Configure(EntityTypeBuilder<EcheanceDesFournisseurs> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.EcheanceDesFournisseurs");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.DateEcheance)
            .HasColumnType("datetime")
            .HasColumnName("dateEcheance");
            entity.Property(e => e.FournisseurId).HasColumnName("fournisseur_id");
            entity.Property(e => e.Montant)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("montant");
            entity.Property(e => e.NumCheque).HasColumnName("numCheque");

            entity.HasOne(d => d.Fournisseur).WithMany(p => p.EcheanceDesFournisseurs)
            .HasForeignKey(d => d.FournisseurId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_dbo.EcheanceDesFournisseurs_dbo.Fournisseur_fournisseur_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EcheanceDesFournisseurs> entity);
    }
}
