// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class FactureAvoirFournisseurConfiguration : IEntityTypeConfiguration<FactureAvoirFournisseur>
    {
        public void Configure(EntityTypeBuilder<FactureAvoirFournisseur> entity)
        {
            entity.HasKey(e => e.Num).HasName("PK_dbo.FactureAvoirFournisseur");

            entity.Property(e => e.Date)
            .HasColumnType("datetime")
            .HasColumnName("date");
            entity.Property(e => e.IdFournisseur).HasColumnName("id_fournisseur");
            entity.Property(e => e.NumFactureAvoirFourSurPage).HasColumnName("Num_FactureAvoirFourSurPAge");
            entity.Property(e => e.NumFactureFournisseur).HasColumnName("Num_FactureFournisseur");

            entity.HasOne(d => d.IdFournisseurNavigation).WithMany(p => p.FactureAvoirFournisseur)
            .HasForeignKey(d => d.IdFournisseur)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_dbo.FactureAvoirFournisseur_dbo.Fournisseur_id_fournisseur");

            entity.HasOne(d => d.NumFactureFournisseurNavigation).WithMany(p => p.FactureAvoirFournisseur)
            .HasForeignKey(d => d.NumFactureFournisseur)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_dbo.FactureAvoirFournisseur_dbo.FactureFournisseur_Num_FactureFournisseur");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FactureAvoirFournisseur> entity);
    }
}
