// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class FactureFournisseurConfiguration : IEntityTypeConfiguration<FactureFournisseur>
    {
        public void Configure(EntityTypeBuilder<FactureFournisseur> entity)
        {
            entity.HasKey(e => e.Num).HasName("PK_dbo.FactureFournisseur");

            entity.Property(e => e.Date)
            .HasColumnType("datetime")
            .HasColumnName("date");
            entity.Property(e => e.DateFacturationFournisseur)
            .HasColumnType("datetime")
            .HasColumnName("dateFacturationFournisseur");
            entity.Property(e => e.IdFournisseur).HasColumnName("id_fournisseur");
            entity.Property(e => e.Paye).HasColumnName("paye");

            entity.HasOne(d => d.IdFournisseurNavigation).WithMany(p => p.FactureFournisseur)
            .HasForeignKey(d => d.IdFournisseur)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_dbo.FactureFournisseur_dbo.Fournisseur_id_fournisseur");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FactureFournisseur> entity);
    }
}
