// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class FactureAvoirFournisseurConfiguration : IEntityTypeConfiguration<FactureAvoirFournisseur>
    {
        public void Configure(EntityTypeBuilder<FactureAvoirFournisseur> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.FactureAvoirFournisseur");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd();

            entity.Property(e => e.Date)
            .HasColumnType("datetime")
            .HasColumnName("date");
            entity.Property(e => e.IdFournisseur).HasColumnName("id_fournisseur");
            entity.Property(e => e.NumFactureAvoirFourSurPage).HasColumnName("Num_FactureAvoirFourSurPAge");
            entity.Property(e => e.FactureFournisseurId).HasColumnName("FactureFournisseurId");
            entity.Property(e => e.Statut)
            .HasConversion<string>()
            .HasMaxLength(50)
            .IsRequired();

            entity.HasOne(d => d.IdFournisseurNavigation).WithMany(p => p.FactureAvoirFournisseur)
            .HasForeignKey(d => d.IdFournisseur)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_dbo.FactureAvoirFournisseur_dbo.Fournisseur_id_fournisseur");

            entity.HasOne(d => d.FactureFournisseurNavigation).WithMany(p => p.FactureAvoirFournisseur)
            .HasForeignKey(d => d.FactureFournisseurId)
            .HasPrincipalKey(p => p.Id)
            .OnDelete(DeleteBehavior.Cascade)
            .HasConstraintName("FK_dbo.FactureAvoirFournisseur_dbo.FactureFournisseur_FactureFournisseurId");

            entity.HasOne(d => d.AccountingYear).WithMany(p => p.FactureAvoirFournisseur)
            .HasForeignKey(d => d.AccountingYearId)
            .OnDelete(DeleteBehavior.Restrict)
            .HasConstraintName("FK_dbo.FactureAvoirFournisseur_dbo.AccountingYear_AccountingYearId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FactureAvoirFournisseur> entity);
    }
}
