// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class FamilleProduitConfiguration : IEntityTypeConfiguration<FamilleProduit>
    {
        public void Configure(EntityTypeBuilder<FamilleProduit> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.FamilleProduit");

            entity.ToTable("FamilleProduit");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("Id");

            entity.Property(e => e.Nom)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("nom");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<FamilleProduit> entity);
    }
}



