// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class FournisseurConfiguration : IEntityTypeConfiguration<Fournisseur>
    {
        public void Configure(EntityTypeBuilder<Fournisseur> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.Fournisseur");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Adresse).HasColumnName("adresse");
            entity.Property(e => e.Code)
            .HasMaxLength(50)
            .HasColumnName("code");
            entity.Property(e => e.CodeCat)
            .HasMaxLength(50)
            .HasColumnName("code_cat");
            entity.Property(e => e.Constructeur).HasColumnName("constructeur");
            entity.Property(e => e.EtbSec)
            .HasMaxLength(50)
            .HasColumnName("etb_sec");
            entity.Property(e => e.Fax)
            .HasMaxLength(50)
            .HasColumnName("fax");
            entity.Property(e => e.Mail).HasColumnName("mail");
            entity.Property(e => e.MailDeux).HasColumnName("mail_deux");
            entity.Property(e => e.Matricule)
            .HasMaxLength(50)
            .HasColumnName("matricule");
            entity.Property(e => e.Nom)
            .HasMaxLength(50)
            .HasColumnName("nom");
            entity.Property(e => e.Tel)
            .HasMaxLength(50)
            .HasColumnName("tel");
            entity.Property(e => e.TauxRetenu)
            .HasColumnName("taux_retenu");
            entity.Property(e => e.ExonereRetenueSource)
            .HasColumnName("exonere_retenue_source");
            entity.Property(e => e.RibCodeEtab)
            .HasMaxLength(10)
            .HasColumnName("rib_code_etab");
            entity.Property(e => e.RibCodeAgence)
            .HasMaxLength(10)
            .HasColumnName("rib_code_agence");
            entity.Property(e => e.RibNumeroCompte)
            .HasMaxLength(20)
            .HasColumnName("rib_numero_compte");
            entity.Property(e => e.RibCle)
            .HasMaxLength(5)
            .HasColumnName("rib_cle");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Fournisseur> entity);
    }
}
