// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class InstallationTechnicianConfiguration : IEntityTypeConfiguration<InstallationTechnician>
    {
        public void Configure(EntityTypeBuilder<InstallationTechnician> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_InstallationTechnician");

            entity.ToTable("InstallationTechnician");

            entity.Property(e => e.Id)
                .HasColumnName("Id")
                .ValueGeneratedOnAdd();

            entity.Property(e => e.Nom)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Nom");

            entity.Property(e => e.Tel)
                .HasMaxLength(50)
                .HasColumnName("Tel");

            entity.Property(e => e.Tel2)
                .HasMaxLength(50)
                .HasColumnName("Tel2");

            entity.Property(e => e.Tel3)
                .HasMaxLength(50)
                .HasColumnName("Tel3");

            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("Email");

            entity.Property(e => e.Description)
                .HasMaxLength(500)
                .HasColumnName("Description");

            entity.Property(e => e.Photo)
                .HasColumnType("nvarchar(max)")
                .HasColumnName("Photo");

            // Index on Nom for search performance
            entity.HasIndex(e => e.Nom)
                .HasDatabaseName("IX_InstallationTechnician_Nom");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<InstallationTechnician> entity);
    }
}
