// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class LigneBonReceptionConfiguration : IEntityTypeConfiguration<LigneBonReception>
    {
        public void Configure(EntityTypeBuilder<LigneBonReception> entity)
        {
            entity.HasKey(e => e.IdLigne).HasName("PK_dbo.LigneBonReception");

            entity.Property(e => e.IdLigne).HasColumnName("Id_ligne");
            entity.Property(e => e.DesignationLi).HasColumnName("designation_li");
            entity.Property(e => e.NumBonRec).HasColumnName("Num_BonRec");
            entity.Property(e => e.PrixHt)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("prix_HT");
            entity.Property(e => e.QteLi).HasColumnName("qte_li");
            entity.Property(e => e.RefProduit)
            .HasMaxLength(50)
            .HasColumnName("Ref_Produit");
            entity.Property(e => e.Remise).HasColumnName("remise");
            entity.Property(e => e.TotHt)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("tot_HT");
            entity.Property(e => e.TotTtc)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("tot_TTC");
            entity.Property(e => e.Tva).HasColumnName("tva");

            entity.HasOne(d => d.NumBonRecNavigation).WithMany(p => p.LigneBonReception)
            .HasForeignKey(d => d.NumBonRec)
            .HasConstraintName("FK_dbo.LigneBonReception_dbo.BonDeReception_Num_BonRec");

            entity.HasOne(d => d.RefProduitNavigation).WithMany(p => p.LigneBonReception)
            .HasForeignKey(d => d.RefProduit)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_dbo.LigneBonReception_dbo.Produit_Ref_Produit");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LigneBonReception> entity);
    }
}
