// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class PrintHistoryConfiguration : IEntityTypeConfiguration<PrintHistory>
    {
        public void Configure(EntityTypeBuilder<PrintHistory> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.PrintHistory");
            
            entity.ToTable("PrintHistory");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("Id");

            entity.Property(e => e.DocumentType)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("DocumentType");

            entity.Property(e => e.DocumentId)
                .IsRequired()
                .HasColumnName("DocumentId");

            entity.Property(e => e.PrintMode)
                .IsRequired()
                .HasConversion<int>()
                .HasColumnName("PrintMode");

            entity.Property(e => e.UserId)
                .HasColumnName("UserId");

            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("Username");

            entity.Property(e => e.PrintedAt)
                .IsRequired()
                .HasColumnType("datetime")
                .HasColumnName("PrintedAt");

            entity.Property(e => e.PrinterName)
                .HasMaxLength(255)
                .HasColumnName("PrinterName");

            entity.Property(e => e.Copies)
                .IsRequired()
                .HasDefaultValue(1)
                .HasColumnName("Copies");

            entity.Property(e => e.FileName)
                .HasMaxLength(500)
                .HasColumnName("FileName");

            entity.Property(e => e.IsDuplicata)
                .IsRequired()
                .HasDefaultValue(false)
                .HasColumnName("IsDuplicata");

            // Indexes for performance
            entity.HasIndex(e => e.DocumentType)
                .HasDatabaseName("IX_PrintHistory_DocumentType");

            entity.HasIndex(e => e.DocumentId)
                .HasDatabaseName("IX_PrintHistory_DocumentId");

            entity.HasIndex(e => e.PrintedAt)
                .HasDatabaseName("IX_PrintHistory_PrintedAt");

            entity.HasIndex(e => new { e.DocumentType, e.DocumentId })
                .HasDatabaseName("IX_PrintHistory_DocumentType_DocumentId");

            entity.HasIndex(e => e.UserId)
                .HasDatabaseName("IX_PrintHistory_UserId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PrintHistory> entity);
    }
}




