// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class ProduitConfiguration : IEntityTypeConfiguration<Produit>
    {
        public void Configure(EntityTypeBuilder<Produit> entity)
        {
            entity.HasKey(e => e.Refe).HasName("PK_dbo.Produit");

            entity.Property(e => e.Refe)
            .HasMaxLength(50)
            .HasColumnName("refe");
            entity.Property(e => e.Nom).HasColumnName("nom");
            entity.Property(e => e.Prix)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("prix");
            entity.Property(e => e.PrixAchat)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("prixAchat");
            entity.Property(e => e.Qte).HasColumnName("qte");
            entity.Property(e => e.QteLimite).HasColumnName("qteLimite");
            entity.Property(e => e.Remise).HasColumnName("remise");
            entity.Property(e => e.RemiseAchat).HasColumnName("remiseAchat");
            entity.Property(e => e.Tva).HasColumnName("TVA");
            entity.Property(e => e.Visibilite).HasColumnName("visibilite");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Produit> entity);
    }
}
