// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class ProduitConfiguration : IEntityTypeConfiguration<Produit>
    {
        public void Configure(EntityTypeBuilder<Produit> entity)
        {
            entity.HasKey(e => e.Refe).HasName("PK_dbo.Produit");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("Id");

            entity.Property(e => e.Refe)
            .HasMaxLength(50)
            .HasColumnName("refe");
            entity.Property(e => e.Nom)
            .HasMaxLength(300)
            .HasColumnName("nom");
            entity.Property(e => e.Prix)
            .HasColumnType("decimal(18, 3)")
            .HasColumnName("prix");
            entity.Property(e => e.PrixAchat)
            .HasColumnType("decimal(18, 3)")
            .HasColumnName("prixAchat");
            entity.Property(e => e.QteLimite).HasColumnName("qteLimite");
            entity.Property(e => e.Remise).HasColumnName("remise");
            entity.Property(e => e.RemiseAchat).HasColumnName("remiseAchat");
            entity.Property(e => e.Tva).HasColumnName("TVA");
            entity.Property(e => e.Visibilite).HasColumnName("visibilite");
            entity.Property(e => e.SousFamilleProduitId).HasColumnName("SousFamilleProduitId");
            entity.Property(e => e.Image1StoragePath).HasColumnName("Image1StoragePath");
            entity.Property(e => e.Image2StoragePath).HasColumnName("Image2StoragePath");
            entity.Property(e => e.Image3StoragePath).HasColumnName("Image3StoragePath");

            entity.HasOne(d => d.SousFamilleProduit)
                .WithMany(p => p.Produits)
                .HasForeignKey(d => d.SousFamilleProduitId)
                .OnDelete(DeleteBehavior.SetNull)
                .HasConstraintName("FK_dbo.Produit_dbo.SousFamilleProduit_SousFamilleProduitId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Produit> entity);
    }
}
