// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class SystemeConfiguration : IEntityTypeConfiguration<Systeme>
    {
        public void Configure(EntityTypeBuilder<Systeme> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_dbo.Systeme");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Adresse).HasColumnName("adresse");
            entity.Property(e => e.AdresseRetenu).HasColumnName("adresseRetenu");
            entity.Property(e => e.CodeCategorie).HasColumnName("codeCategorie");
            entity.Property(e => e.CodeTva).HasColumnName("codeTVA");
            entity.Property(e => e.Email).HasColumnName("email");
            entity.Property(e => e.EtbSecondaire).HasColumnName("etbSecondaire");
            entity.Property(e => e.Fax).HasColumnName("fax");
            entity.Property(e => e.MatriculeFiscale).HasColumnName("matriculeFiscale");
            entity.Property(e => e.NomSociete).HasMaxLength(50);
            entity.Property(e => e.PourcentageFodec)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("pourcentageFodec");
            entity.Property(e => e.PourcentageRetenu).HasColumnName("pourcentageRetenu");
            entity.Property(e => e.Tel).HasColumnName("tel");
            entity.Property(e => e.Timbre).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.VatAmount)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("VatAmount");
            entity.Property(e => e.DiscountPercentage)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("DiscountPercentage");
            entity.Property(e => e.VatRate0)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("VatRate0");
            entity.Property(e => e.VatRate7)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("VatRate7");
            entity.Property(e => e.VatRate13)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("VatRate13");
            entity.Property(e => e.VatRate19)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("VatRate19");
            entity.Property(e => e.BloquerVenteStockInsuffisant)
            .HasColumnName("BloquerVenteStockInsuffisant")
            .HasDefaultValue(true);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Systeme> entity);
    }
}
