// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using TunNetCom.SilkRoadErp.Sales.Domain.Entites;

#nullable disable

namespace TunNetCom.SilkRoadErp.Sales.Domain.Entites.Configurations
{
    public partial class TransactionConfiguration : IEntityTypeConfiguration<Transaction>
    {
        public void Configure(EntityTypeBuilder<Transaction> entity)
        {
            entity.HasKey(e => e.BonDeLivraisonId).HasName("PK_dbo.Transaction");

            entity.Property(e => e.BonDeLivraisonId)
            .ValueGeneratedNever()
            .HasColumnName("BonDeLivraisonId");
            entity.Property(e => e.DateTr)
            .HasColumnType("datetime")
            .HasColumnName("date_tr");
            entity.Property(e => e.Montant)
            .HasColumnType("decimal(18, 2)")
            .HasColumnName("montant");
            entity.Property(e => e.Type).HasColumnName("type");

            entity.HasOne(d => d.NumBlNavigation).WithOne(p => p.Transaction)
            .HasForeignKey<Transaction>(d => d.BonDeLivraisonId)
            .OnDelete(DeleteBehavior.ClientSetNull)
            .HasConstraintName("FK_dbo.Transaction_dbo.BonDeLivraison_BonDeLivraisonId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Transaction> entity);
    }
}
